"""empty message

Revision ID: 0df1b43d9c73
Revises: 70ac64574372
Create Date: 2019-12-26 22:43:18.652544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df1b43d9c73'
down_revision = '70ac64574372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_id', sa.Integer(), nullable=False),
    sa.Column('pass_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zan')
    # ### end Alembic commands ###
