"""empty message

Revision ID: 77ce4e5ac20f
Revises: e4b5e2599fe1
Create Date: 2019-12-27 19:49:50.528925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ce4e5ac20f'
down_revision = 'e4b5e2599fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('n_zan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibo', 'n_zan')
    # ### end Alembic commands ###
